/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return API health status, database connection, and model metadata.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/head-to-head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Head To Head
         * @description Predict match outcome probabilities using chosen architecture.
         */
        post: operations["predict_head_to_head_api_v1_predictions_head_to_head_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare Predictions
         * @description Return side-by-side comparison of Dixon-Coles and XGBoost predictions.
         */
        post: operations["compare_predictions_api_v1_predictions_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fixtures/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Upcoming Fixtures
         * @description Return scheduled upcoming fixtures with dual-model predictions.
         */
        get: operations["list_upcoming_fixtures_api_v1_fixtures_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Teams
         * @description Return all teams the model knows about.
         */
        get: operations["list_teams_api_v1_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_name}/strengths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Strength
         * @description Return a team's attack and defense strength parameters (Dixon-Coles).
         */
        get: operations["get_team_strength_api_v1_teams__team_name__strengths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_name}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Profile
         * @description Return comprehensive team profile combining Poisson and rolling XGBoost stats.
         */
        get: operations["get_team_profile_api_v1_teams__team_name__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComparePredictionResponse */
        ComparePredictionResponse: {
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            dixon_coles: components["schemas"]["ModelPredictionBlock"];
            xgboost: components["schemas"]["ModelPredictionBlock"];
        };
        /** FixtureCard */
        FixtureCard: {
            /** Id */
            id: number;
            /** Gameweek */
            gameweek: number;
            /** Kickoff Time */
            kickoff_time: string;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /** Status */
            status: string;
            /** Predictions */
            predictions: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeadToHeadRequest
         * @description Request body for a head-to-head prediction.
         */
        HeadToHeadRequest: {
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Model Loaded */
            model_loaded: boolean;
            /** Database Connected */
            database_connected: boolean;
            /** Models */
            models: {
                [key: string]: components["schemas"]["ModelStatus"];
            };
            /** Message */
            message?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * MatchPrediction
         * @description Full prediction for a match.
         */
        MatchPrediction: {
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /** Prob Home */
            prob_home: number;
            /** Prob Draw */
            prob_draw: number;
            /** Prob Away */
            prob_away: number;
            predicted_score?: components["schemas"]["ScorePrediction"] | null;
            /** Score Distribution */
            score_distribution?: number[][] | null;
            /** Model */
            model: string;
        };
        /** ModelPredictionBlock */
        ModelPredictionBlock: {
            /** Prob Home */
            prob_home: number;
            /** Prob Draw */
            prob_draw: number;
            /** Prob Away */
            prob_away: number;
            predicted_score?: components["schemas"]["ScorePrediction"] | null;
            /** Score Distribution */
            score_distribution?: number[][] | null;
            /** Features */
            features?: {
                [key: string]: unknown;
            } | null;
        };
        /** ModelStatus */
        ModelStatus: {
            /** Loaded */
            loaded: boolean;
            /** Version */
            version?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ScorePrediction
         * @description Predicted most likely score.
         */
        ScorePrediction: {
            /** Home */
            home: number;
            /** Away */
            away: number;
        };
        /** TeamProfileResponse */
        TeamProfileResponse: {
            /** Team */
            team: string;
            /** Dixon Coles */
            dixon_coles: {
                [key: string]: number;
            };
            /** Xgboost */
            xgboost: {
                [key: string]: unknown;
            };
        };
        /**
         * TeamStrength
         * @description Attack and defense strengths for a team.
         */
        TeamStrength: {
            /** Team */
            team: string;
            /** Attack */
            attack: number;
            /** Defense */
            defense: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    predict_head_to_head_api_v1_predictions_head_to_head_post: {
        parameters: {
            query?: {
                model?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeadToHeadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPrediction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_predictions_api_v1_predictions_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeadToHeadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparePredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_upcoming_fixtures_api_v1_fixtures_upcoming_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureCard"][];
                };
            };
        };
    };
    list_teams_api_v1_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_team_strength_api_v1_teams__team_name__strengths_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamStrength"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_profile_api_v1_teams__team_name__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
